[package]
name = "complexipy-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[lib]
name = "complexipy_core"

[features]
python = ["dep:pyo3", "complexipy-types/python"]

[dependencies]
complexipy-types = { path = "../complexipy-types" }
ruff_python_parser = { workspace = true }
ruff_python_ast = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
csv = { workspace = true }
ignore = { workspace = true }
wax = { workspace = true }
rayon = { workspace = true }
pyo3 = { workspace = true, optional = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
